### ISSUE TITLE
Add About us page

### ISSUE THREAD

**Issue by ashToronto** [ashToronto/career_crafter_pro#78]
Create a new page called "about" add a link for it in the footer somewhere.

You'll need to update is `app/views/home/index.html.haml` and add a `link_to` tag, this is essentially an href but the rails way of routing. 

Add some text around the company and what we do (i'll leave it to you to decide what to add in the about section) - check out what competitors do - like the site you showed me i.e `simplify`

You will need to create this new page - here's a checklist: 
- you will need to update the `routes.rb` file and add a new route
- next you will add a controller action which is essentially the rest endpoint for the `about` page 
- finally you can create an `about.html.haml` file and add your front end code - leverage bootstrap 5 for quick and easy css - be mindful where you create this file and it's convention. Rails matches controllers and views by naming convention. 
- ensure it is mobile responsive - bootstrap 5 will handle this for you most of the time

Learning outcomes and resources: By the end of this ticket you will know how to create new pages that are stati, traverse/debug front end code, handle routing (basics). 

Here are some resources to help you through it: 

-> [basic haml tutorial video 5 mins watch](https://www.youtube.com/watch?v=lmwekfagApw)

-> [html to haml online converter](https://awsm-tools.com/html-to-haml) - tooling to help you get familiar with haml

-> [bootstrap 5 documentation for css needs](https://getbootstrap.com/docs/5.0/layout/containers/) - you shouldn't need to add any css - most of our layouts are covered by bootstrap 5 follow the patterns you come across. 

-> [Build an about page - controllers and views](https://www.youtube.com/watch?v=XCBcyocNMt8) - this is the exact task you will do - most important video to watch. it's one to one with your task.

If you feel you want to learn more about the ruby programming language i.e arrays, primitive types, loops, etc: 

-> [Ruby coding fundemetals](https://www.youtube.com/watch?v=8wZ2ZD--VTk) - 30-40 mins watch and practice

**Comment by ykomarlu** [comment]
[https://www.figma.com/design/QfkDJ1u4uO2N5x4pI2qLkg/About-Page?node-id=0-1&t=Q8viXCYKSKhYjyU5-1](url)

**Comment by ashToronto** [comment]
Yup looks amazing only feedback - be mindful of mobile responsive - otherwise you're looking good and on track

**Comment by ashToronto** [comment]
I went ahead and did the minimum for the linkedin page, feel free to leverage the URL in this ticket: 

`https://www.linkedin.com/company/career-crafter-pro/`

**Comment by ykomarlu** [comment]
done!
