### ISSUE TITLE
Onboard Daniel Macbook - rvm

### ISSUE THREAD

**Issue by ashToronto** [ashToronto/career_crafter_pro#80]
-> We will first setup your local mac with both ruby 3.0.0 and rvm - ruby version manager (lets you switch ruby versions)
-> Next we will setup Rails 7.1.2 - matches the application specs
-> Finally we'll setup postgres sql and install and setup a gui so you can visualize the database.

We can now clone the repo once prerequisites are done. 

Step 1: Install Homebrew or ensure you have it running on your mac. 

Step 2: Install GPG
`brew install gpg`

Step 3: Install RVM - ruby version manager 

-> Import the GPG keys:
`gpg --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB`

-> Install RVM:
`\curl -sSL https://get.rvm.io | bash -s stable`

-> Load RVM:
`source ~/.rvm/scripts/rvm`

Step 4: Install Ruby 3.0.0

`rvm install 3.0.0`

`rvm use 3.0.0 --default` -> to use 3.0.0 as the default version

at this point if everything worked out you should be able to run `rvm list` and see a list of all your installed ruby versions on your local.  Also running `ruby -v` should output ruby version 3.0.0 

Step 5: Install Rails 7.1.2
`gem install rails -v 7.1.2`

if rails installed correctly you will be able to see 7.1.2 as the version when you run `rails -v`
 

You will also need postgresSql to run the application - set this up also. 

step 1: Install Postgres on mac with brew: 
`brew install postgresql`

Step 2 start postgres locally: 
`brew services start postgresql`

step 3 Verify the installation by connecting to the PostgreSQL server:
`psql postgres`

**Comment by SpicyNachos03** [comment]
-> Import the GPG keys:
- Had an issue with installing the GPG keys due to a "Network error," I ended up downloading the keys directly from their server with shell commands:
`curl -sSL https://rvm.io/mpapis.asc | gpg --import -`
`curl -sSL https://rvm.io/pkuczynski.asc | gpg --import -`

Step 4: Install Ruby 3.0.0
`rvm install "ruby-3.0.0"` instead of `rvm install 3.0.0` worked for me to install ruby

**Comment by ashToronto** [comment]
To setup a psql role 

`psql postgres` - this connects you to your postgres sql shell `\q` to quit the shell.

Once inside the shell: 

`CREATE ROLE myappuserName WITH LOGIN PASSWORD 'myapppassword';`
This sets up a pgsql role with privileges 

Now set these values in your `application.yml` file and trigger the database creation with `rake db:setup`
application.yml is a gitignored file similar to your .env file - it holds all secrets for your setup and local operations.

**Comment by ashToronto** [comment]
create a file called `application.yml` it should be in the root of the project. If you're using vs code it might also be greyed out (cuz its gitignored). 

There should be 2 key value pairs in this at minimum, representing your environment variables. 

   POSTGRES_USER: myappuserNam 
  POSTGRES_PASSWORD: myapppassword

myappuserNam & myapppassword  are from the last step i.e when you setup your Postgres role. 

Now run `bundle install`

Now follow readme and setup database with `rake db:setup` followed my `rails s` 

you should no longer see the db connection error.
